/********************************************************************
* rootdict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error rootdict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablerootdict();
extern void G__cpp_setup_inheritancerootdict();
extern void G__cpp_setup_typetablerootdict();
extern void G__cpp_setup_memvarrootdict();
extern void G__cpp_setup_globalrootdict();
extern void G__cpp_setup_memfuncrootdict();
extern void G__cpp_setup_funcrootdict();
extern void G__set_cpp_environmentrootdict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "pdpcevent.h"
#include "GemEvent.h"
#include "PDPCFarichHitData.h"
#include "PDPCFarichRecoHit.h"
#include "PDPCFarichRecoEvent.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__rootdictLN_TClass;
extern G__linked_taginfo G__rootdictLN_TBuffer;
extern G__linked_taginfo G__rootdictLN_TMemberInspector;
extern G__linked_taginfo G__rootdictLN_TObject;
extern G__linked_taginfo G__rootdictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__rootdictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__rootdictLN_TClonesArray;
extern G__linked_taginfo G__rootdictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__rootdictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__rootdictLN_PdpcHit;
extern G__linked_taginfo G__rootdictLN_GemCluster;
extern G__linked_taginfo G__rootdictLN_PDPCFarichHitData;
extern G__linked_taginfo G__rootdictLN_PDPCFarichRecoHit;
extern G__linked_taginfo G__rootdictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__rootdictLN_PDPCFarichRecoEvent;
extern G__linked_taginfo G__rootdictLN_vectorlETClonesArraymUcOallocatorlETClonesArraymUgRsPgR;
extern G__linked_taginfo G__rootdictLN_reverse_iteratorlEvectorlETClonesArraymUcOallocatorlETClonesArraymUgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
