/********************************************************************
* PDPCFarichRootDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error PDPCFarichRootDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablePDPCFarichRootDict();
extern void G__cpp_setup_inheritancePDPCFarichRootDict();
extern void G__cpp_setup_typetablePDPCFarichRootDict();
extern void G__cpp_setup_memvarPDPCFarichRootDict();
extern void G__cpp_setup_globalPDPCFarichRootDict();
extern void G__cpp_setup_memfuncPDPCFarichRootDict();
extern void G__cpp_setup_funcPDPCFarichRootDict();
extern void G__set_cpp_environmentPDPCFarichRootDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/podgornov/exbeam/git/reconstruction/PDPCFarich/PDPCFarichGeometry.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__PDPCFarichRootDictLN_TClass;
extern G__linked_taginfo G__PDPCFarichRootDictLN_TBuffer;
extern G__linked_taginfo G__PDPCFarichRootDictLN_TMemberInspector;
extern G__linked_taginfo G__PDPCFarichRootDictLN_TObject;
extern G__linked_taginfo G__PDPCFarichRootDictLN_TString;
extern G__linked_taginfo G__PDPCFarichRootDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__PDPCFarichRootDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR;
extern G__linked_taginfo G__PDPCFarichRootDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__PDPCFarichRootDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__PDPCFarichRootDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__PDPCFarichRootDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__PDPCFarichRootDictLN_PDPCFarichGeometry;
extern G__linked_taginfo G__PDPCFarichRootDictLN_PDPCFarichGeometrycLcLGeometry;
extern G__linked_taginfo G__PDPCFarichRootDictLN_PDPCFarichGeometrycLcLTile;
extern G__linked_taginfo G__PDPCFarichRootDictLN_maplEintcOPDPCFarichGeometrycLcLTilecOlesslEintgRcOallocatorlEpairlEconstsPintcOPDPCFarichGeometrycLcLTilegRsPgRsPgR;

/* STUB derived class for protected member access */
