/********************************************************************
* TreeFormatsRootDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TreeFormatsRootDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTreeFormatsRootDict();
extern void G__cpp_setup_inheritanceTreeFormatsRootDict();
extern void G__cpp_setup_typetableTreeFormatsRootDict();
extern void G__cpp_setup_memvarTreeFormatsRootDict();
extern void G__cpp_setup_globalTreeFormatsRootDict();
extern void G__cpp_setup_memfuncTreeFormatsRootDict();
extern void G__cpp_setup_funcTreeFormatsRootDict();
extern void G__set_cpp_environmentTreeFormatsRootDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/podgornov/exbeam/git/TreeFormats/pdpcevent.h"
#include "/home/podgornov/exbeam/git/TreeFormats/GemEvent.h"
#include "/home/podgornov/exbeam/git/TreeFormats/PDPCFarichHitData.h"
#include "/home/podgornov/exbeam/git/TreeFormats/PDPCFarichRecoEvent.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TreeFormatsRootDictLN_TClass;
extern G__linked_taginfo G__TreeFormatsRootDictLN_TBuffer;
extern G__linked_taginfo G__TreeFormatsRootDictLN_TMemberInspector;
extern G__linked_taginfo G__TreeFormatsRootDictLN_TObject;
extern G__linked_taginfo G__TreeFormatsRootDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TreeFormatsRootDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TreeFormatsRootDictLN_TClonesArray;
extern G__linked_taginfo G__TreeFormatsRootDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TreeFormatsRootDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TreeFormatsRootDictLN_PdpcHit;
extern G__linked_taginfo G__TreeFormatsRootDictLN_GemCluster;
extern G__linked_taginfo G__TreeFormatsRootDictLN_PDPCFarichHitData;
extern G__linked_taginfo G__TreeFormatsRootDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TreeFormatsRootDictLN_PDPCFarichRecoHit;
extern G__linked_taginfo G__TreeFormatsRootDictLN_PDPCFarichRecoEvent;
extern G__linked_taginfo G__TreeFormatsRootDictLN_vectorlETClonesArraymUcOallocatorlETClonesArraymUgRsPgR;
extern G__linked_taginfo G__TreeFormatsRootDictLN_reverse_iteratorlEvectorlETClonesArraymUcOallocatorlETClonesArraymUgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
